
import React, { useEffect } from 'react';
// Fix: Import useApp from its source context file
import { useApp } from '../context/AppContext.tsx';
import { FileText, Shield, Gavel } from 'lucide-react';

const TermsOfService: React.FC = () => {
  const { language } = useApp();
  const isAr = language === 'ar';

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-white min-h-screen pb-24" dir={isAr ? 'rtl' : 'ltr'}>
      <div className="relative h-[500px] flex flex-col items-center justify-center text-center px-6 overflow-hidden">
        <div className="absolute inset-0 z-0">
          <img 
            src="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1600&q=80" 
            className="w-full h-full object-cover grayscale opacity-20"
            alt="Legal background"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-brand-dark/30 to-white" />
        </div>
        
        <div className="relative z-10 space-y-6">
           <Gavel size={48} className="mx-auto text-brand-dark" />
           <h1 className="text-6xl md:text-8xl font-serif font-bold text-brand-dark tracking-tighter">
             {isAr ? 'شروط الخدمة' : 'Terms of Service'}
           </h1>
           <p className="text-brand-dark/40 font-medium uppercase tracking-[0.5em]">Central Protocol v1.0</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-20 space-y-16">
        <section className="space-y-4">
          <h2 className="text-2xl font-serif font-bold text-brand-dark">1. Acceptance of Terms</h2>
          <p className="text-brand-dark/60 leading-relaxed">
            By accessing and using Coffee Old Town Lab, you accept and agree to be bound by the terms and provision of this agreement. Our AI-driven analysis is for informational purposes only.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-serif font-bold text-brand-dark">2. AI Analysis & Medical Disclaimer</h2>
          <p className="text-brand-dark/60 leading-relaxed">
            The nutritional information generated by our Gemini-powered engine does not constitute medical advice. Always consult with a certified healthcare professional before making significant dietary changes.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-serif font-bold text-brand-dark">3. User Responsibility</h2>
          <p className="text-brand-dark/60 leading-relaxed">
            Users are responsible for the images they upload to our scanner. We do not store personal biometric data unless explicitly requested via clinical protocols.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfService;
